create or replace TRIGGER travel_AI 
BEFORE INSERT  ON TRAVEL
FOR EACH ROW
DECLARE 
v_ID TRAVEL.TRAVEL_ID%TYPE ;
BEGIN 
	SELECT MAX_ID INTO v_ID FROM TRAVEL_STATUS ts ;
	IF v_ID IS NOT NULL THEN
		:new.TRAVEL_ID := v_ID+1;
	ELSE
		:new.TRAVEL_ID := 1;
	END IF;
END;