CREATE OR REPLACE FORCE EDITIONABLE VIEW ARRIVAL_TO_STATION ("TRAVEL_ID", "STATION_ID", "MIN", "ARRIVE_TIME") AS 
select TRAVEL_ID, STATION_ID, 
getTimeArrival(ls.LINE_ID, 1, ls.STATION_ID) as MIN, 
TO_TIMESTAMP(
to_char(
t.START_TIME + (1/1440)*getTimeArrival(ls.LINE_ID, 1, ls.STATION_ID),'DD/MM/YY HH24:MI:SS'),'DD/MM/YY HH24:MI:SS') as ARRIVE_TIME 
from TRAVEL t, LINE_STOP ls where t.LINE_ID = ls.LINE_ID ORDER BY ORDER_STOP ASC;