DELETE TICKET;
DELETE TRAVEL;
DELETE DELTA_TIME_STATION;
DELETE LINE_STOP;
DELETE LINE;
DELETE PLATFORM;
DELETE STATION;
DELETE CITY;
DELETE REGION;
DELETE COUNTRY;
DELETE DRIVER_ABILITY;
DELETE DRIVER;
DELETE EMPLOYEES_DATA;
DELETE EMPLOYEE_CATEGORIE;
DELETE COMPANY;
DELETE USER_DATA;
DELETE USER_CATEGORIE;
DELETE TRAIN;
DELETE TRAIN_TYPE;
DELETE TRAIN_STATUS;

ALTER TABLE TICKET DROP CONSTRAINT FK_TICKET_USER;
ALTER TABLE TICKET DROP CONSTRAINT FK_TICKET_TRAVEL;
ALTER TABLE TICKET DROP CONSTRAINT FK_TICKET_START_STATION_ID;
ALTER TABLE TICKET DROP CONSTRAINT FK_TICKET_END_STATION_ID;
ALTER TABLE TICKET DROP CONSTRAINT PK_TICKET;
DROP TABLE TICKET;

ALTER TABLE TRAVEL DROP CONSTRAINT FK_TRAVEL_LINE;
ALTER TABLE TRAVEL DROP CONSTRAINT FK_TRAVEL_TRAIN_ID;
ALTER TABLE TRAVEL DROP CONSTRAINT FK_TRAVEL_DRIVER;
ALTER TABLE TRAVEL DROP CONSTRAINT PK_TRAVEL;
DROP TABLE TRAVEL;

ALTER TABLE DELTA_TIME_STATION DROP CONSTRAINT CK_DELTA_TIME;
ALTER TABLE DELTA_TIME_STATION DROP CONSTRAINT FK_DELTA_START_STATION_ID;
ALTER TABLE DELTA_TIME_STATION DROP CONSTRAINT FK_DELTA_END_STATION_ID;
ALTER TABLE DELTA_TIME_STATION DROP CONSTRAINT PK_DELTA;
DROP TABLE DELTA_TIME_STATION;

ALTER TABLE LINE_STOP DROP CONSTRAINT FK_LINE_STOP_LINE_ID;
ALTER TABLE LINE_STOP DROP CONSTRAINT FK_LINE_STOP_STATION_ID;
ALTER TABLE LINE_STOP DROP CONSTRAINT PK_LINE_STOP;
DROP TABLE LINE_STOP;

ALTER TABLE LINE DROP CONSTRAINT CK_DIFF_START_END;
ALTER TABLE LINE DROP CONSTRAINT FK_LINE_START_STATION_ID;
ALTER TABLE LINE DROP CONSTRAINT FK_LINE_END_STATION_ID;
ALTER TABLE LINE DROP CONSTRAINT PK_LINE;
DROP TABLE LINE;

ALTER TABLE PLATFORM DROP CONSTRAINT CK_PLATFORM_STATUS;
ALTER TABLE PLATFORM DROP CONSTRAINT CK_PLATFORM_UTILISATION;
ALTER TABLE PLATFORM DROP CONSTRAINT FK_PLATFORM_STATION_ID;
ALTER TABLE PLATFORM DROP CONSTRAINT PK_PLATFORM;
DROP TABLE PLATFORM;

ALTER TABLE STATION DROP CONSTRAINT FK_STATION_CITY_ID;
ALTER TABLE STATION DROP CONSTRAINT PK_STATION_ID;
DROP TABLE STATION;

ALTER TABLE CITY DROP CONSTRAINT PK_CITY_ID;
ALTER TABLE CITY DROP CONSTRAINT FK_CITY_REGION_ID;
DROP TABLE CITY;

ALTER TABLE REGION DROP CONSTRAINT FK_REGION_COUNTRY_ID;
ALTER TABLE REGION DROP CONSTRAINT PK_REGION_ID;
DROP TABLE REGION;

ALTER TABLE COUNTRY DROP CONSTRAINT PK_COUNTRY;
DROP TABLE COUNTRY;

ALTER TABLE DRIVER_ABILITY DROP CONSTRAINT FK_DRIVER_ABILITY_DRIVER_ID;
ALTER TABLE DRIVER_ABILITY DROP CONSTRAINT FK_DRIVER_ABILITY_TRAIN_TYPE;
ALTER TABLE DRIVER_ABILITY DROP CONSTRAINT PK_DRIVER_ABILITY;
DROP TABLE DRIVER_ABILITY;

ALTER TABLE DRIVER DROP CONSTRAINT FK_DRIVER;
ALTER TABLE DRIVER DROP CONSTRAINT PK_DRIVER;
DROP TABLE DRIVER;

ALTER TABLE EMPLOYEES_DATA DROP CONSTRAINT FK_EMPLOYEE_USER;
ALTER TABLE EMPLOYEES_DATA DROP CONSTRAINT FK_EMPLOYEE_COMPANY;
ALTER TABLE EMPLOYEES_DATA DROP CONSTRAINT FK_EMPLOYEE_ACCESS;
ALTER TABLE EMPLOYEES_DATA DROP CONSTRAINT PK_EMPLOYEE;
DROP TABLE EMPLOYEES_DATA;

ALTER TABLE EMPLOYEE_CATEGORIE DROP CONSTRAINT PK_EMPLOYEE_CATEGORIE;
DROP TABLE EMPLOYEE_CATEGORIE;

ALTER TABLE COMPANY DROP CONSTRAINT PK_COMPANY;
DROP TABLE COMPANY;

ALTER TABLE USER_DATA DROP CONSTRAINT FK_USER_CATEGORIE;
ALTER TABLE USER_DATA DROP CONSTRAINT PK_USER;
DROP TABLE USER_DATA;

ALTER TABLE USER_CATEGORIE DROP CONSTRAINT PK_USER_CATEGORIE;
DROP TABLE USER_CATEGORIE;

ALTER TABLE TRAIN DROP CONSTRAINT FK_TRAIN_TYPE;
ALTER TABLE TRAIN DROP CONSTRAINT FK_TRAIN_STATUS;
ALTER TABLE TRAIN DROP CONSTRAINT PK_TRAIN;
DROP TABLE TRAIN;

ALTER TABLE TRAIN_TYPE DROP CONSTRAINT PK_TRAIN_TYPE;
DROP TABLE TRAIN_TYPE;

ALTER TABLE TRAIN_STATUS DROP CONSTRAINT PK_TRAIN_STATUS;
DROP TABLE TRAIN_STATUS;

CREATE TABLE TRAIN_STATUS
(
    TRAIN_STATUS_ID INT NOT NULL,
    TRAIN_STATUS_LABEL VARCHAR2(255) NOT NULL,

    CONSTRAINT PK_TRAIN_STATUS PRIMARY KEY (TRAIN_STATUS_ID)
);

CREATE TABLE TRAIN_TYPE
(
    TRAIN_TYPE_ID INT NOT NULL,
    TRAIN_TYPE_LABEL VARCHAR2(255) NOT NULL,
    TRAIN_CAPACITY INT NOT NULL,
    TRAIN_SPEED INT NOT NULL,
    TRAIN_LENGTH FLOAT NOT NULL,

    CONSTRAINT PK_TRAIN_TYPE PRIMARY KEY (TRAIN_TYPE_ID)
);

CREATE TABLE TRAIN
(
    TRAIN_ID INT NOT NULL,
    TRAIN_TYPE_ID INT NOT NULL,
    TRAIN_STATUS_ID INT DEFAULT 0,
    
    CONSTRAINT PK_TRAIN PRIMARY KEY (TRAIN_ID),
    CONSTRAINT FK_TRAIN_TYPE FOREIGN KEY (TRAIN_TYPE_ID) REFERENCES TRAIN_TYPE(TRAIN_TYPE_ID),
    CONSTRAINT FK_TRAIN_STATUS FOREIGN KEY (TRAIN_STATUS_ID) REFERENCES TRAIN_STATUS(TRAIN_STATUS_ID)
);

/*##################################################################*/
CREATE TABLE USER_CATEGORIE
(
    USER_CATEGORIE_ID INT NOT NULL,
    USER_CATEGORIE_LABEL VARCHAR2(255) NOT NULL,

    CONSTRAINT PK_USER_CATEGORIE PRIMARY KEY (USER_CATEGORIE_ID)
);
    
CREATE TABLE USER_DATA
(
    USER_ID INT NOT NULL,
    USER_MAIL VARCHAR2(255) NOT NULL,
    USER_PHONE VARCHAR2(10),
    USER_PASSWORD VARCHAR2(255) NOT NULL,
    USER_LASTNAME VARCHAR2(255) NOT NULL,
    USER_FIRSTNAME VARCHAR2(255) NOT NULL,
    USER_CATEGORIE_ID INT DEFAULT 0,

    CONSTRAINT PK_USER PRIMARY KEY (USER_ID),
    CONSTRAINT FK_USER_CATEGORIE FOREIGN KEY (USER_CATEGORIE_ID) REFERENCES USER_CATEGORIE(USER_CATEGORIE_ID)
);

CREATE TABLE COMPANY
(
    COMPANY_ID INT NOT NULL,
    COMPANY_NAME VARCHAR2(255) NOT NULL,

    CONSTRAINT PK_COMPANY PRIMARY KEY (COMPANY_ID) 
);

CREATE TABLE EMPLOYEE_CATEGORIE
(
    EMPLOYEE_CATEGORIE_ID INT NOT NULL,
    EMPLOYEE_CATEGORIE_LABEL VARCHAR2(255) NOT NULL,

    CONSTRAINT PK_EMPLOYEE_CATEGORIE PRIMARY KEY (EMPLOYEE_CATEGORIE_ID)
);

CREATE TABLE EMPLOYEES_DATA
(
    USER_ID INT NOT NULL,
    COMPANY_ID INT NOT NULL,
    EMPLOYEE_ACCESS INT NOT NULL,

    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (USER_ID),
    CONSTRAINT FK_EMPLOYEE_USER FOREIGN KEY (USER_ID) REFERENCES USER_DATA(USER_ID),
    CONSTRAINT FK_EMPLOYEE_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY(COMPANY_ID),
    CONSTRAINT FK_EMPLOYEE_ACCESS FOREIGN KEY (EMPLOYEE_ACCESS) REFERENCES EMPLOYEE_CATEGORIE(EMPLOYEE_CATEGORIE_ID)
);

CREATE TABLE DRIVER
(
    DRIVER_ID INT NOT NULL,
    USER_ID INT NOT NULL UNIQUE,

    CONSTRAINT PK_DRIVER PRIMARY KEY (DRIVER_ID),
    CONSTRAINT FK_USER FOREIGN KEY (USER_ID) REFERENCES EMPLOYEES_DATA(USER_ID)
);

CREATE TABLE DRIVER_ABILITY
(
    DRIVER_ID INT NOT NULL,
    TRAIN_TYPE_ID INT NOT NULL,
    
    CONSTRAINT PK_DRIVER_ABILITY PRIMARY KEY (DRIVER_ID,TRAIN_TYPE_ID),
    CONSTRAINT FK_DRIVER_ABILITY_DRIVER_ID FOREIGN KEY (DRIVER_ID) REFERENCES DRIVER(DRIVER_ID),
    CONSTRAINT FK_DRIVER_ABILITY_TRAIN_TYPE FOREIGN KEY (TRAIN_TYPE_ID) REFERENCES TRAIN_TYPE(TRAIN_TYPE_ID)
);
/*##################################################################*/
CREATE TABLE COUNTRY
(
    COUNTRY_ID INT NOT NULL,
    COUNTRY_NAME VARCHAR2(255) NOT NULL,
    COUNTRY_LABEL VARCHAR2(2) NOT NULL,

    CONSTRAINT PK_COUNTRY PRIMARY KEY (COUNTRY_ID)
);

CREATE TABLE REGION
(
    REGION_ID INT NOT NULL,
    COUNTRY_ID INT NOT NULL,
    REGION_NAME VARCHAR2(255) NOT NULL,

    CONSTRAINT PK_REGION_ID PRIMARY KEY (COUNTRY_ID,REGION_ID),
    CONSTRAINT FK_REGION_COUNTRY_ID FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY(COUNTRY_ID)
);

CREATE TABLE CITY
(
    CITY_ID INT NOT NULL,
    COUNTRY_ID INT NOT NULL,
    REGION_ID INT NOT NULL,
    POSTAL INT,
    CITY_NAME VARCHAR2(255) NOT NULL,


    CONSTRAINT PK_CITY_ID PRIMARY KEY (CITY_ID),
    CONSTRAINT FK_CITY_REGION_ID FOREIGN KEY (COUNTRY_ID,REGION_ID) REFERENCES REGION(COUNTRY_ID,REGION_ID)
);
/*##################################################################*/
CREATE TABLE STATION 
(
    STATION_ID INT NOT NULL,
    CITY_ID INT NOT NULL,
    STATION_NAME VARCHAR2(255) NOT NULL,

    CONSTRAINT PK_STATION_ID PRIMARY KEY (STATION_ID),
    CONSTRAINT FK_STATION_CITY_ID FOREIGN KEY (CITY_ID) REFERENCES CITY(CITY_ID)
);

CREATE TABLE PLATFORM
(
    PLATFORM_LETTER VARCHAR2(1) NOT NULL,
    TERMINAL_ID INT NOT NULL,
    STATION_ID INT NOT NULL,
    PLATFORM_STATUS INT DEFAULT 0,
    PLATFORM_UTILISATION INT DEFAULT 0,
    PLATFORM_USER INT,
    PLATFORM_LENGTH FLOAT NOT NULL,

    CONSTRAINT PK_PLATFORM PRIMARY KEY (PLATFORM_LETTER,TERMINAL_ID,STATION_ID),
    CONSTRAINT FK_PLATFORM_STATION_ID FOREIGN KEY (STATION_ID) REFERENCES STATION(STATION_ID),
    CONSTRAINT CK_PLATFORM_STATUS CHECK (PLATFORM_STATUS = 1 OR PLATFORM_STATUS = 0),
    CONSTRAINT CK_PLATFORM_UTILISATION CHECK (PLATFORM_UTILISATION = 1 OR PLATFORM_UTILISATION = 0)
);

/*##################################################################*/
CREATE TABLE LINE
(
    LINE_ID INT NOT NULL,
    START_STATION_ID INT NOT NULL,
    END_STATION_ID INT NOT NULL,

    CONSTRAINT PK_LINE PRIMARY KEY (LINE_ID),
    CONSTRAINT FK_LINE_START_STATION_ID FOREIGN KEY (START_STATION_ID) REFERENCES STATION(STATION_ID),
    CONSTRAINT FK_LINE_END_STATION_ID FOREIGN KEY (END_STATION_ID) REFERENCES STATION(STATION_ID),
    CONSTRAINT CK_DIFF_START_END CHECK (START_STATION_ID != END_STATION_ID)
);

CREATE TABLE LINE_STOP
(
    LINE_ID INT NOT NULL,
    STATION_ID INT NOT NULL,
    ORDER_STOP INT NOT NULL,
    DURATION_TIME INT NOT NULL,

    CONSTRAINT PK_LINE_STOP PRIMARY KEY (LINE_ID,STATION_ID),
    CONSTRAINT FK_LINE_STOP_LINE_ID FOREIGN KEY (LINE_ID) REFERENCES LINE(LINE_ID),
    CONSTRAINT FK_LINE_STOP_STATION_ID FOREIGN KEY (STATION_ID) REFERENCES STATION(STATION_ID)
);

CREATE TABLE DELTA_TIME_STATION
(
    START_STATION_ID INT NOT NULL,
    END_STATION_ID INT NOT NULL,
    DELTA_TIME INT NOT NULL,

    CONSTRAINT PK_DELTA PRIMARY KEY (START_STATION_ID,END_STATION_ID),
    CONSTRAINT FK_DELTA_START_STATION_ID FOREIGN KEY (START_STATION_ID) REFERENCES STATION(STATION_ID),
    CONSTRAINT FK_DELTA_END_STATION_ID FOREIGN KEY (END_STATION_ID) REFERENCES STATION(STATION_ID),
    CONSTRAINT CK_DELTA_TIME CHECK (DELTA_TIME > 0)
);
/*##################################################################*/
CREATE TABLE TRAVEL
(
    TRAVEL_ID INT NOT NULL,
    TRAVEL_DATETIME DATE NOT NULL,
    LINE_ID INT NOT NULL,
    TRAIN_ID INT NOT NULL,
    DRIVER_ID INT NOT NULL,
    END_DATETIME TIMESTAMP,
    START_TIME TIMESTAMP,
    LATE_TIME INT,

    CONSTRAINT PK_TRAVEL PRIMARY KEY (TRAVEL_ID),
    CONSTRAINT FK_TRAVEL_LINE FOREIGN KEY (LINE_ID) REFERENCES LINE(LINE_ID),
    CONSTRAINT FK_TRAVEL_TRAIN_ID FOREIGN KEY (TRAIN_ID) REFERENCES TRAIN(TRAIN_ID),
    CONSTRAINT FK_TRAVEL_DRIVER FOREIGN KEY (DRIVER_ID) REFERENCES DRIVER(DRIVER_ID)
);

CREATE TABLE TICKET
(
    USER_ID INT NOT NULL,
    TRAVEL_ID INT NOT NULL,
    START_STATION_ID INT NOT NULL,
    END_STATION_ID INT NOT NULL,

    CONSTRAINT PK_TICKET PRIMARY KEY (USER_ID,TRAVEL_ID),
    CONSTRAINT FK_TICKET_USER FOREIGN KEY (USER_ID) REFERENCES USER_DATA(USER_ID),
    CONSTRAINT FK_TICKET_TRAVEL FOREIGN KEY (TRAVEL_ID) REFERENCES TRAVEL(TRAVEL_ID),
    CONSTRAINT FK_TICKET_START_STATION_ID FOREIGN KEY (START_STATION_ID) REFERENCES STATION(STATION_ID),
    CONSTRAINT FK_TICKET_END_STATION_ID FOREIGN KEY (END_STATION_ID) REFERENCES STATION(STATION_ID)

);