create or replace FUNCTION GETTIMESTOP 
(
PLINE_ID IN NUMBER,
  PSTATION_ID IN NUMBER 
) RETURN NUMBER AS 
v_time NUMBER;
BEGIN
    SELECT DURATION_TIME INTO V_TIME FROM LINE_STOP WHERE STATION_ID = PSTATION_ID AND LINE_ID = PLINE_ID;
  RETURN v_time;
END GETTIMESTOP;